[package]
name = "minidb"
version = "0.1.0"
authors = ["yui-knk <spiketeika@gmail.com>"]

[dependencies]
clap = "*"
libc = "*"
tempfile = "*"
byteorder = "*"
errno = "*"
log = "*"
simple_logger = "*"
